### ISSUE TITLE
unable to load DLL 'gdal_wrap'

### ISSUE THREAD

**Issue by mamont80** [MaxRev-Dev/gdal.netcore#140]
I use the combination MaxRev.Gdal.Core + MaxRev.Gdal.WindowsRuntime.Minimal version 3.9.0.218 on .Net Framework 4.8.

There is a problem; on some(!) machines it throws an exception:
"unable to load DLL 'gdal_wrap': The specified module could not be found."
However, on some servers everything works fine.
I checked on 4 computers: it works on 2, it doesn’t work on 2. Those that work have other programs.
I checked on "clean" Windows 10. It doesn't work.
I'm guessing it's some kind of dependency issue. Installed Microsoft Visual C++ 2015-2022 Redistributable (x64). It did not help.

I checked the previous version 3.8.3.259. It works on all computers!
But the previous version did not copy the GDAL binaries when building to the version for .Net Framwork 4.8.
I had to manually add them from the nuget package.
In the .NET 8 version of the software everything was fine, the DLLs were in the build directory.

**Comment by MaxRev-Dev** [comment]
See #137.

**Comment by OWiger** [comment]
I'm also trying to figure out this problem. 
I'm building a simple .NET 8.0 Console application with MaxRev.Gdal.Core (3.9.1.244) and MaxRev.Gdal.WindowsRuntime.Minimal (3.9.1.244).

Program.cs:
using MaxRev.Gdal.Core; 
GdalBase.ConfigureAll(); 
Console.WriteLine("Hello, World!");

I build this project in release mode. On my dev-machine, it works fine. Hello world is displayed.

If I copy the entire net8.0 build-folder to a freshly created azure VM with Windows 11 (or windows 10), and try to run the application I get:
`Unhandled exception. System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.AllRegister()
   at OSGeo.GDAL.Gdal.AllRegister()
   at MaxRev.Gdal.Core.GdalBase.ConfigureGdalDrivers(String gdalDataFolder)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
   at Program.<Main>$(String[] args) in C:\Users\ow\source\repos\TestGdalApp\Program.cs:line 4`

I have the following runtimes and redistributables installed on the vm:

![image](https://github.com/user-attachments/assets/f4c2bd08-1bf7-4003-ba5b-b001402fbd63)
