### ISSUE TITLE
[BUG] Unable to load shared library 'gdal_wrap' or one of its dependencies In CentOS 7

### ISSUE THREAD

**Issue by LGinC** [MaxRev-Dev/gdal.netcore#156]
````bash
$ sudo dotnet Web.Host.dll

Unhandled exception. System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'gdal_wrap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgdal_wrap: cannot open shared object file: No such file or directory
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.AllRegister()
   at OSGeo.GDAL.Gdal.AllRegister()
   at MaxRev.Gdal.Core.GdalBase.ConfigureGdalDrivers(String gdalDataFolder)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
````  

**Environment information:**
 - OS (version): CentOS 7 
 - Package version (core): 3.9.1.247
 - Package version (runtime): 3.9.1.247

```bash
$ glib-compile-resources --version
2.56.1
```

```xml
<ItemGroup>
  <PackageReference Include="MaxRev.Gdal.Core" Version="3.9.1.247" />
  <PackageReference Include="MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.9.1.247" />
  <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.9.1.247" />
</ItemGroup>
```

**Comment by MaxRev-Dev** [comment]
@LGinC CentOS 7 is not supported anymore. Consider moving to another system or use docker.
Read [this doc section](https://github.com/MaxRev-Dev/gdal.netcore?tab=readme-ov-file#q-packages-does-not-work-on-centos-7-ubuntu-1804).

**Comment by MaxRev-Dev** [comment]
@LGinC  This requires advanced manual setup.

1. Set `GdalBase.EnableRuntimeValidation = false;`. Before calling `GdalBase.ConfigureAll(); `
2. Install native binaries and find the native dll files location `<GdalFolder>\bin\gdal\csharp`. Link them (add a reference) in your `csproj` project file to each  `gdal_csharp.dll, gdalconst_csharp.dll, ogr_csharp.dll and osr_csharp.`.

So I wouldn't recommend this. The bindings are being compiled during the GDAL build and this generates corresponding C# interface. Binaries are placed in the same directory, so the startup knows what to utilize.
You need either to use CLI tools or dockerized .NET app with GDAL packages.

**Comment by LGinC** [comment]
@MaxRev-Dev  thx
I found it change proj.db search directory and it work
```CSharp
if(OperatingSystem.IsLinux())
{
    GdalBase.EnableRuntimeValidation = false;
    GdalBase.ConfigureGdalDrivers();
    Proj.Configure("/usr/local/share/proj/");
}
else
    GdalBase.ConfigureAll();
```

**Comment by xd2020** [comment]
I read that  , do I need to install gdal?

**Comment by MaxRev-Dev** [comment]
@xd2020 yes, you have to install [gdal binaries](https://gis.stackexchange.com/questions/263495/how-to-install-gdal-on-centos-7-4). Otherwise, you need to [dockerize](https://github.com/MaxRev-Dev/gdal.netcore/blob/main/tests/MaxRev.Gdal.Core.Tests/Dockerfile) your application.
