### ISSUE TITLE
Error loading HDF5 on Windows 10

### ISSUE THREAD

**Issue by MaxRev-Dev** [MaxRev-Dev/gdal.netcore#158]
I have the following installed:
maxRev.Gdal.Core 3.9.1.247
maxRev.Gdal.Universal 3.9.1.247
maxRev.Gdal.WindowsRuntime.Minimal 3.9.1.247

We found that this seems to be missing as a dependency of gdal_wrap.dll. I am not sure if this is exactly the same issue as stated above, otherwise I can also open a new issue. But it seems very similar. @MaxRev-Dev I am not sure if you can reproduce this and maybe this fix via this issue already. 
![image](https://github.com/user-attachments/assets/a3bc8675-37ad-4e7e-8ff1-fd60e36c82ff)

Here is my error code. For what I can see exactly the same as the error message that @dawsidious received. 

<details><summary>Log</summary>
<p>

```

System.TypeInitializationException
The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
   at OSGeo.GDAL.GdalPINVOKE.AllRegister()
   at OSGeo.GDAL.Gdal.AllRegister()
   at MaxRev.Gdal.Core.GdalBase.ConfigureGdalDrivers(String gdalDataFolder)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
   at AiChangeDetectionModel.Services.AiChangeDetectionModelService.SaveArrayTif(DenseTensor`1 imgArrayOutput, String name, ValueTuple`2 upperLeft) in C:\DevOpsIT\GIS.Viewer\BorePlannerZonderBP\src\AiChangeDetectionModel\Services\AiChangeDectectionModelService.cs:line 158
   at AiChangeDetectionModel.Services.AiChangeDetectionModelService.Run() in C:\DevOpsIT\GIS.Viewer\BorePlannerZonderBP\src\AiChangeDetectionModel\Services\AiChangeDectectionModelService.cs:line 66
   at AiChangeDetectionModel.Tests.AiChangeDetectionModelServiceTests.TestRunAiChangeDetectionModel() in C:\DevOpsIT\GIS.Viewer\BorePlannerZonderBP\src\AiChangeDetectionModel.Tests\AiChangeDetectionModelServiceTests.cs:line 11
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0() in /_/src/xunit.execution/Sdk/AsyncTestSyncContext.cs:line 58

System.TypeInitializationException
The type initializer for 'SWIGExceptionHelper' threw an exception.
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()

System.DllNotFoundException
Unable to load DLL 'gdal_wrap' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
```

</p>
</details> 

_Originally posted by @sjoertiej in https://github.com/MaxRev-Dev/gdal.netcore/issues/150#issuecomment-2357690443_

**Comment by MaxRev-Dev** [comment]
@sjoertiej This could be a wrong version of HDF5 library packaged. Please, create a MRE and attach it here to a comment.
