### ISSUE TITLE
Can't find proj.db folder from package in project output directory [BUG]

### ISSUE THREAD

**Issue by Gigas002** [MaxRev-Dev/gdal.netcore#3]
**Describe the bug**

I've created a little library (netcore3.0, x64) which uses MaxRev.Gdal.Core and MaxRev.Gdal.WindowsRuntime.Minimal packages. Then I've referenced this library from console application. Now when I'm trying to call `GdalBase.ConfigureAll();` it throws exceptions:

```text
The type initializer for 'OSGeo.OSR.OsrPINVOKE' threw an exception.
Can't find proj.db folder from package in project output directory
Error in MaxRev.Gdal.Core, Version=3.0.1.2, Culture=neutral, PublicKeyToken=null
System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
The type initializer for 'SWIGExceptionHelper' threw an exception.
```

**To Reproduce**

Empty console app on netcore3.0 has the same issue, can be tested here. Just reference mentioned nuget packages and call `GdalBase.ConfigureAll();`

**Expected behavior**

Gdal initilazed successfully.

**Environment information:**
 - OS (version): Windows 10 (1903)
 - Package version (core): 3.0.1.2
 - Package version (runtime): 3.0.1.2

**Comment by MaxRev-Dev** [comment]
I can't reproduce that. Seems like you have a cyrillic chars in your project path. In the **compile** folder there is a configurator class source. You may copy it, fix/debug locally and make a PR, that would be great.  

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/24393967/66868206-9631d000-efa5-11e9-9457-a280a498e7d0.png)
</details>

**Comment by Gigas002** [comment]
Thanks for quick answer. No, I don't have cyrillic symbols in path. Path string looks like this: `C:\Users\gigas\Documents\Visual Studio 2019\Projects\NewGdalTest\NewGdalTest\bin\x64\Debug\netcoreapp3.0`. I tried using code fron [configurator class](https://github.com/MaxRev-Dev/gdal.netcore/blob/master/compile/GdalConfigureAll.cs) directly, and found out, that there are two exceptions are thrown at line 71: `OSGeo.GDAL.Gdal.SetConfigOption("GDAL_DRIVER_PATH", targetDrivers);`

Inner exceptions are following:
`TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.`
and
`DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: Не найден указанный модуль. (0x8007007E)`

**Comment by MaxRev-Dev** [comment]
Please, checkout if **jpeg.dll** exists in your project output folder. This library is required by **HDF4.dll** and must be loaded firstly. Maybe it cannot be found in package folder from the nuget cache.
<details>
<summary>My project output</summary>

![image](https://user-images.githubusercontent.com/24393967/66871612-adc08700-efac-11e9-9cc4-cd7bfa3133be.png)
</details>

**Comment by MaxRev-Dev** [comment]
Here is my test project on [GDrive](https://drive.google.com/open?id=1mVuC-xydzMl-SVOCw1tSp8HziY3EKg2H)
1.  If you are referencing your library (wrapper) directly in solution, It should work as is.
2.  Referencing a DLL of your library - you must build the library project with 
       ```dotnet build -c Release -r win-x64 -o your_output_folder```
If even after this solutions you won't be able to load libraries - provide your test sources.

**Comment by Gigas002** [comment]
Yes, mentioned files does exist in output directories. Unfortunately, your solution from google drive too throws exceptions for me.
[Here's](https://github.com/MaxRev-Dev/gdal.netcore/files/3735450/NewGdalTest.zip) a little console project, that throws exceptions without referencing any `.dll`.
I've tested it on another **Win10** and **Win7 (SP1)** x64 PCs and had the same errors. Two thrown exceptions are following:

```text
System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.BadImageFormatException: Была сделана попытка загрузить программу, имеющую неверный формат. (0x8007000B)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at NewGdalTest.GdalBase.ConfigureAll() in I:\tests\NewGdalTest\GdalBase.cs:line 72
Unhandled exception. System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.BadImageFormatException: Была сделана попытка загрузить программу, имеющую неверный формат. (0x8007000B)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at NewGdalTest.GdalBase.ConfigureAll() in I:\tests\NewGdalTest\GdalBase.cs:line 102
   at NewGdalTest.Program.Main(String[] args) in I:\tests\NewGdalTest\Program.cs:line 9
```

What's interesting, on my first Win10 PC the exception is different (it seems unable to find `gdal_wrap.dll`):
```text
Unhandled exception. System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at NewGdalTest.GdalBase.ConfigureAll() in D:\NewGdalTest\GdalBase.cs:line 72
   at NewGdalTest.Program.Main(String[] args) in D:\NewGdalTest\Program.cs:line 9
```

I've also tested the same project with your linux runtime package, and it seems to work fine (tested on **KDE Neon (Ubuntu) x64**).

**Comment by MaxRev-Dev** [comment]
Found a missing dependency library (**geos_c.dll -> libwinpthread-1.dll**).
Setting up a VM with pure Win7 to check the entire build.
With linux it's much easier, I use **ldd** to copy all dependent libraries.

**Comment by Gigas002** [comment]
Thanks, copying this `.dll` to `runtimes\win-x64\native` directory solves the problem!
